#!/bin/bash

if [[ $(id -u) -ne 0 ]]; then
  echo "sudo please"
  exit 1
fi

##remove docker
apt remove docker docker-engine docker.io containerd runc

#set up the repository
apt update
apt install -y apt-transport-https ca-certificates curl gnupg-agent software-properties-common
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -

add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"

#install docker ce
apt install -y docker-ce docker-ce-cli containerd.io

#add sailor user non-interactively
adduser --disabled-password --gecos "" sailor
usermod -aG docker sailor

#2
su - sailor -c 'docker run -it ubuntu:16.04 bash'
