#!/bin/bash

#set -x
# sudo check
id=$(id -u);

if [ "$id" -ne 0 ]
	then echo "Run script by sudo"
	exit 0;
fi

# task 1
if
	dpkg -l | grep nginx
	then
		ver=$(nginx -v 2>&1)
		apt purge nginx --yes
		echo "nginx $ver removed"
	else
		echo "nginx not installed"
fi

# task 2
apt update
apt install curl gnupg2 ca-certificates lsb-release --yes
echo "deb http://nginx.org/packages/ubuntu `lsb_release -cs` nginx" \
	| tee /etc/apt/sources.list.d/nginx.list
curl -fsSL https://nginx.org/keys/nginx_signing.key | apt-key add -
#apt-key fingerprint ABF5BD827BD9BF62
apt update
apt install nginx=1.14.2*

cp /etc/nginx/nginx.conf /etc/nginx/nginxbckp.conf
mkdir /etc/nginx/sites-available/ /etc/nginx/sites-enabled/
sed -i '/http {/a include /etc/nginx/sites-enabled/\*.conf;' /etc/nginx/nginx.conf
#sed -i '$ d' /etc/nginx/nginx.conf && echo -e "include /etc/ngnix/sites-enabled\*.conf;\n}">> /etc/nginx/nginx.conf
mv /etc/nginx/conf.d/default.conf /etc/nginx/sites-available/
ln -s /etc/nginx/sites-available/default.conf /etc/nginx/sites-enabled/

service nginx restart

curl 127.0.0.1 | grep -om 1 "Welcome to nginx"

# task 3
REDL='\033[1;31m'
ps -lfC nginx | grep 'master' | awk '{print "Nginx main process have a PID:" $4}';
echo -en "Nginx number of worker processes: $REDL $(ps -aux | grep nginx | grep -c worker)$REDL"
#ps -lFC nginx | grep 'worker' | awk '{print "Nginx worker process: \33[0;31m" $4}';
#LRED='\033[1;31m'
#echo -n
#awk '{print "Nginx main process have a PID:"; print $0}' /var/run/nginx.pid
#echo -en "Nginx number of 'worker' processes: $LRED $(pcs -aux | grep nginx | grep -c worker)$LRED"

